version: '2.2'

services:
  nextapp:
    container_name: cosmo-mix
    image: cosmo-mix
    build: .
    ports:
      - "3000:3000"
    restart: always
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - nextapp
