version: '3.7'

services:
  app:
    container_name: nextjs_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8081:80
    restart: unless-stopped
