name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Backend Docker image
        run: docker build -t rotquecksilber/cosmo-mix .

      - name: Push Backend Docker image
        run: docker push rotquecksilber/cosmo-mix

      - name: Clone repository on server
        run: |
          echo "$DEPLOY_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem -o "StrictHostKeyChecking=no" ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "cd /home/${{ secrets.SERVER_USERNAME }}/cosmo-mix && git pull"
        env:
          DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to server
        run: |
          echo "$DEPLOY_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem -o "StrictHostKeyChecking=no" ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} <<EOF
            cd /home/${{ secrets.SERVER_USERNAME }}/cosmo-mix
            docker-compose down
            docker-compose pull
            docker-compose up -d
            docker image prune -f
          EOF
        env:
          DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
